<?php

use Illuminate\Database\Seeder;
use App\History;
use App\LetterSoup;
use App\Tests;
use App\Point;

class HistorySeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $history = History::create([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Noé',
            'sub_title' => 'Noé y el Gran Diluvio',
            'description' => 'Fascinante historia sobre la construcción de un arca y el pacto de Dios con el mundo',
            'content' => 'Fascinante historia sobre la construcción de un arca y el pacto de Dios con el mundo',
            'image' => 'images/histories/10-06-2018_20-06-12.jpeg',
            'video' => 'videos/histories/node.mp4',
        ]);

            LetterSoup::create([
                'history_id' => $history->id,
                'words' => '[{"word":"NOE","id":1528782759442},{"word":"ARCA","id":1528782791175},{"word":"AGUA","id":1528782799168},{"word":"LLUVIA","id":1528782800295},{"word":"MACHO","id":1528782800767},{"word":"HEMBRA","id":1528782801160},{"word":"DIAS","id":1528782801552},{"word":"PALOMA","id":1528782801912}]',
            ]);

                $history->memores()->create([
                    "image" => "images/memories/noe/1e5bd080-6e60-11e8-b892-2593a06b90d8.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/2beec9d0-6e60-11e8-b8a2-516b1f8bea62.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/3358c310-6e60-11e8-bb80-ddeb86cc137f.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/3c22dcc0-6e60-11e8-8ee9-017d87f4e60d.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/44c8a3f0-6e60-11e8-af37-ed1bfe1ec5b8.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/4d499ab0-6e60-11e8-8d4e-2de92e638a0b.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/555d5570-6e60-11e8-a305-19becf7e83b6.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/5efaab00-6e60-11e8-88de-9d2ae7d922b2.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/67b9be70-6e60-11e8-9fb6-9fa5658b4889.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/739e5ba0-6e60-11e8-b896-ff273f8cfb34.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/8102f290-6e60-11e8-8e72-59fe71339ec0.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/8ff7acd0-6e60-11e8-9668-db5fa1266313.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/99034800-6e60-11e8-8cbd-ad995ff34bec.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/a2dc9b10-6e60-11e8-903c-952bc6393f66.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/ad1614b0-6e60-11e8-8a75-1b7d199e190c.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/baa987a0-6e60-11e8-afcf-af258cb3b6e0.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/c367e870-6e60-11e8-bb7d-9778da9080a6.png",
                ]);
                $history->memores()->create([
                    "image" => "images/memories/noe/cc0908e0-6e60-11e8-b2d5-b32bf7c458b0.png",
                ]);

        $history = History::create([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Abraham',
            'sub_title' => 'Dios prueba el amor de Abraham',
            'description' => 'Un hombre escogido por Dios, lleno de fe y amor.',
            'content' => 'Un hombre escogido por Dios, lleno de fe y amor.',
            'image' => 'images/histories/10-06-2018_20-06-43.jpeg',
            'video' => 'videos/histories/abraham.mp4',
        ]);

            LetterSoup::create([
                'history_id' => $history->id,
                'words' => '[{"word":"AMOR","id":1528782624400},{"word":"HIJO","id":1528782671617},{"word":"ALTO","id":1528782681889},{"word":"ISAAC","id":1528782689280},{"word":"\u00c1NGEL","id":1528782694256},{"word":"ORDEN","id":1528782698280},{"word":"PRUEBA","id":1528782701002},{"word":"ALTAR","id":1528782705729},{"word":"ABRAHAM","id":1528782708264},{"word":"TEMOR","id":1528782715192}]',
            ]);

        $history = History::create([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sansón',
            'sub_title' => 'Sansón el hombre fuerte de Dios',
            'description' => 'Un hombre increíblemente fuerte, que pasará por una dura prueba, para demostrar su obediencia',
            'content' => 'Un hombre increíblemente fuerte, que pasará por una dura prueba, para demostrar su obediencia',
            'image' => 'images/histories/10-06-2018_20-06-32.jpeg',
            'video' => 'videos/histories/sanson.mp4',
        ]);

            LetterSoup::create([
                'history_id' => $history->id,
                'words' => '[{"word":"BEBE","id":1528782233656},{"word":"JUEZ","id":1528782267482},{"word":"ASNO","id":1528782279354},{"word":"MANOA","id":1528782287234},{"word":"ISRAEL","id":1528782295842},{"word":"FUERTE","id":1528782308410},{"word":"CORTAR","id":1528782317441},{"word":"QUIJADA","id":1528782323257}]',
            ]);


        //Historias (Pre-Jueveniles)

        $history = History::create([
            'user_id' => 1,
            'category_id' => 2,
            'title' => 'Noé',
            'sub_title' => 'Noé y el Gran Diluvio',
            'description' => 'fascinante historia sobre la construcción de un arca y el pacto de Dios con el mundo',
            'content' => '<!DOCTYPE html>
                            <html>
                            <head>
                            </head>
                            <body>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: center;" align="center"><span style="color: #0070c0;"><span style="font-family: Courgette, serif;"><span style="font-size: x-large;"><span lang="es-ES"><strong>No&eacute; y el Gran Diluvio</strong></span></span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: center;" align="center">&nbsp;</p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">No&eacute; era un hombre que adoraba a Dios.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">La dem&aacute;s gente lo odiaba y desobedec&iacute;a, un d&iacute;a Dios dijo algo sorprendente </span></span></span><span style="color: #0070c0;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">&ldquo;Voy a destruir este mundo perverso&rdquo;</span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES"> y le dijo a No&eacute; &ldquo;Solamente tu familia ser&aacute; salvada&rdquo;, le advirti&oacute; que un gran diluvio iba a venir que cubrir&iacute;a la tierra.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="color: #0070c0;">&ldquo;<span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Haz un arca de madera, un barco muy, muy grande como para tu familia y muchos animales&rdquo;</span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES"> le orden&oacute; a No&eacute;.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Dios le dio instrucciones exactas de c&oacute;mo construirlo y No&eacute; se apresur&oacute; a trabajar.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">La gente se burlaba mientras No&eacute; explicaba porque estaba construyendo un arca, construy&oacute; y habl&oacute; a la gente acerca de Dios pero nadie le escuch&oacute;.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">No&eacute; crey&oacute; en Dios aunque aun no llegaba la lluvia; De pronto el arca estuvo lista para llenar con provisiones, y Dios orden&oacute; a los animales de todas las especies macho y hembra como p&aacute;jaros grandes y peque&ntilde;os, bestias chiquitas y altas y todas se dirigieron hacia el arca.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">La gente se burlaba mientras ve&iacute;an entrar los animales, ellos no dejaban de pecar contra Dios, al final todos los animales estaban dentro del arca y Dios dijo </span></span></span><span style="color: #0070c0;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">&ldquo;Sube al arca t&uacute; y tu familia&rdquo;,</span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES"> No&eacute; su esposa, sus tres hijos y las esposas de ellos entraron al arca, luego Dios cerr&oacute; la puerta. Despu&eacute;s vino la lluvia, un chaparr&oacute;n enorme el cu&aacute;l mojo toda la tierra por cuarenta d&iacute;as y cuarenta noches, el agua inund&oacute; ciudades, pueblos y monta&ntilde;as estaban bajo agua, todo lo que respiraba aire estaba muerto, mientras que el agua sub&iacute;a el arca flotaba.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Luego de cinco meses de inundaci&oacute;n Dios mando un viento secador, lentamente el arca fue a parar al alto de las monta&ntilde;as de Ararat. No&eacute; se qued&oacute; dentro cuarenta d&iacute;as m&aacute;s mientras el agua iba bajando. No&eacute; mando un cuervo y una paloma por la ventana, para ver si encontraban un lugar seco en donde descansar, la paloma volvi&oacute; a No&eacute;. Una semana m&aacute;s tarde No&eacute; prob&oacute; de nuevo. La paloma volvi&oacute; con una hoja de olivo en el pico. A la semana siguiente No&eacute; env&iacute;o nuevamente a la paloma supo que la tierra estaba seca porque la paloma no volvi&oacute;. </span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Dios le dijo a No&eacute; que era tiempo de irse del arca, junto con su familia descargaron a los animales, &iexcl;Cu&aacute;n agradecido se habr&iacute;a sentido No&eacute;!, que construy&oacute; un altar y ador&oacute; a Dios quien le hab&iacute;a salvado a &eacute;l y a su familia del terrible diluvio. Dios le prometi&oacute; a No&eacute; nunca m&aacute;s mandar&iacute;a un diluvio para juzgar el pecado humano.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Dios le dio un gran recuerdo que fue el arco&iacute;ris era la se&ntilde;al de su promesa.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">No&eacute; y su familia encontraron nuevas tierras donde vivir. Con el paso del tiempo, sus descendientes repoblaron la tierra entera. Todas las naciones del mundo vinieron de No&eacute; y sus hijos.</span></span></span></p>
                            </body>
                            </html>',
            'image' => 'images/histories/10-06-2018_21-06-30.jpeg',
            'video' => '',
        ]);

            LetterSoup::create([
                'history_id' => $history->id,
                'words' => '[{"word":"NOE","id":1528782759442},{"word":"ARCA","id":1528782791175},{"word":"AGUA","id":1528782799168},{"word":"LLUVIA","id":1528782800295},{"word":"MACHO","id":1528782800767},{"word":"HEMBRA","id":1528782801160},{"word":"DIAS","id":1528782801552},{"word":"PALOMA","id":1528782801912},{"word":"ARCOIRIS","id":1528782827185},{"word":"ANIMALES","id":1528782827544}]',
            ]);

        $tests = Tests::create([
            'history_id' => $history->id,
            'questions' => '[{"id":null,"_id":"15486822081717Iare","question":"Pregunta 1","options":[{"op":"Opci\u00f3n","check":false,"_id":1548682208171},{"op":"Opci\u00f3n","check":false,"_id":1548682208172},{"op":"Opci\u00f3n","check":false,"_id":1548682208172},{"op":"BN","check":true,"_id":1548682208172}]},{"id":null,"_id":"154868220817390LmG","question":"Pregunta 2","options":[{"op":"Opci\u00f3n","check":false,"_id":1548682208173},{"op":"Opci\u00f3n","check":false,"_id":1548682208173},{"op":"Opci\u00f3n","check":false,"_id":1548682208173},{"op":"BN","check":true,"_id":1548682208173}]},{"id":null,"_id":"1548682208173p9s8W","question":"Pregunta 3","options":[{"op":"Opci\u00f3n","check":false,"_id":1548682208173},{"op":"Opci\u00f3n","check":false,"_id":1548682208173},{"op":"Opci\u00f3n","check":false,"_id":1548682208173},{"op":"BN","check":true,"_id":1548682208173}]},{"id":null,"_id":"1548682208174ck1M7","question":"Pregunta 4","options":[{"op":"Opci\u00f3n","check":false,"_id":1548682208174},{"op":"Opci\u00f3n","check":false,"_id":1548682208174},{"op":"Opci\u00f3n","check":false,"_id":1548682208174},{"op":"BN","check":true,"_id":1548682208174}]},{"id":null,"_id":"1548682208174M4r6t","question":"Pregunta 5","options":[{"op":"Opci\u00f3n","check":false,"_id":1548682208174},{"op":"Opci\u00f3n","check":false,"_id":1548682208174},{"op":"Opci\u00f3n","check":false,"_id":1548682208174},{"op":"BN","check":true,"_id":1548682208174}]}]',
            'second_question' => '25'
        ]);

        $history = History::create([
            'user_id' => 1,
            'category_id' => 2,
            'title' => 'Abraham',
            'sub_title' => 'Dios prueba el amor de Abraham',
            'description' => 'un hombre escogido por Dios, lleno de fe y amor.',
            'content' => '<!DOCTYPE html>
                            <html>
                            <head>
                            </head>
                            <body>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: center;" align="center"><span style="color: #ff0000;"><span style="font-family: Courgette, serif;"><span style="font-size: x-large;"><span lang="es-ES"><strong>Dios prueba el amor de Abraham</strong></span></span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: center;" align="center">&nbsp;</p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Una noche Dios le dio a Abraham una orden extra&ntilde;a, era una prueba para ver si Abraham amaba a su hijo Isaac m&aacute;s que a Dios </span></span></span><span style="color: #ff0000;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">&ldquo;lleva a tu hijo Isaac y ofr&eacute;cele como un sacrificio&rdquo;</span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES"> le orden&oacute; Dios. Esto era dif&iacute;cil para Abraham, &eacute;l amaba mucho a su hijo. Pero Abraham hab&iacute;a aprendido a confiar en Dios a&uacute;n cuando no entend&iacute;a. </span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">El pr&oacute;ximo d&iacute;a a la ma&ntilde;ana sali&oacute; para ir a la monta&ntilde;a de sacrificio con Isaac y dos sirvientes, antes de salir, Abraham cort&oacute; pedazos de madera para hacer un fuego para el sacrificio. Abraham planeaba obedecer a Dios, tres d&iacute;as m&aacute;s tarde se acercaron a la monta&ntilde;a. </span></span></span><span style="color: #ff0000;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">&ldquo;Qu&eacute;dense ac&aacute;&rdquo;</span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES"> Abraham les dijo a sus sirvientes. </span></span></span><span style="color: #ff0000;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">&ldquo;Nosotros iremos y adoraremos y volveremos a ustedes&rdquo;.</span></span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Isaac cargo la madera, Abraham llev&oacute; el fuego y un cuchillo, Isaac pregunt&oacute; &iquest;Adonde est&aacute; el cordero para el sacrificio?, &ldquo;</span></span></span><span style="color: #ff0000;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Dios se proveer&aacute; de Cordero&rdquo;</span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES"> respondi&oacute; Abraham, los dos vinieron al lugar exacto escogido por Dios.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">All&iacute;, Abraham construy&oacute; un altar y puso la madera para quemar el sacrificio ante Dios. Abraham at&oacute; a Isaac a su hijo amado sobre el altar y cuando se dispon&iacute;a al sacrificio de su hijo, aunque su coraz&oacute;n se part&iacute;a, pero Abraham sab&iacute;a que ten&iacute;a que obedecer a Dios. </span></span></span><span style="color: #ff0000;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">&ldquo;ALTO&rdquo; </span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">grit&oacute; el &Aacute;ngel de Dios </span></span></span><span style="color: #ff0000;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">&ldquo;Ahora sabe Dios que le temes, no has desobedecido&rdquo; </span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">y</span></span></span> <span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">viendo un cordero en los arbustos, el &aacute;ngel le dijo que le sacrificara en lugar de Isaac y mientras que Abraham e Isaac adoraban a Dios el &aacute;ngel de Dios le habl&oacute; a Abraham </span></span></span><span style="color: #ff0000;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">&ldquo;En tu descendencia ser&aacute;n todas las naciones bendecidas porque tu obedeciste&rdquo;.</span></span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Alg&uacute;n d&iacute;a cientos de a&ntilde;os despu&eacute;s Jes&uacute;s ser&iacute;a nacido a trav&eacute;s de los descendientes de Abraham.</span></span></span></p>
                            </body>
                            </html>',
            'image' => 'images/histories/10-06-2018_21-06-18.jpeg',
            'video' => '',
        ]);

            LetterSoup::create([
                'history_id' => $history->id,
                'words' => '[{"word":"AMOR","id":1528782624400},{"word":"HIJO","id":1528782671617},{"word":"ALTO","id":1528782681889},{"word":"ISAAC","id":1528782689280},{"word":"\u00c1NGEL","id":1528782694256},{"word":"ORDEN","id":1528782698280},{"word":"PRUEBA","id":1528782701002},{"word":"ALTAR","id":1528782705729},{"word":"ABRAHAM","id":1528782708264},{"word":"TEMOR","id":1528782715192},{"word":"AMADO","id":1528782715408},{"word":"CONFIAR","id":1528782724641}]',
            ]);

        $history = History::create([
            'user_id' => 1,
            'category_id' => 2,
            'title' => 'Sansón',
            'sub_title' => 'Sansón el hombre fuerte de Dios',
            'description' => 'un hombre increíblemente fuerte, que pasará por una dura prueba, para demostrar su obediencia',
            'content' => '<!DOCTYPE html>
                            <html>
                            <head>
                            </head>
                            <body>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: center;" align="center"><span style="color: #9bbb59;"><span style="font-family: Courgette, serif;"><span style="font-size: x-large;"><span lang="es-ES"><strong>Sans&oacute;n el hombre fuerte de Dios</strong></span></span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: center;" align="center">&nbsp;</p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Hace muchos a&ntilde;os, en Israel, vivi&oacute; un hombre llamado Manoa, el y su esposa no ten&iacute;an hijos. Un d&iacute;a un &aacute;ngel de Dios apareci&oacute; a la esposa de Manoa </span></span></span><span style="color: #9bbb59;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">&ldquo;Tendr&aacute;s un beb&eacute; muy especial&rdquo; </span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">le dijo el &aacute;ngel y cuando ella le cont&oacute; a su esposo el oro diciendo </span></span></span><span style="color: #9bbb59;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">&ldquo;Ah Se&ntilde;or m&iacute;o&hellip; que aquel var&oacute;n de Dios que enviaste, vuelva ahora a venir a nosotros y nos ense&ntilde;e lo que tenemos que hacer con el ni&ntilde;o que ha de nacer&rdquo;</span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">. El &aacute;ngel dijo a Manoa que el ni&ntilde;o </span></span></span><span style="color: #9bbb59;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">nunca deb&iacute;a</span></span></span></span> <span style="color: #9bbb59;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">cortarse el cabello, nunca beber licor, ni comer ciertas comidas</span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES"> porque Dios hab&iacute;a escogido este ni&ntilde;o para ser un juez que gobernar&iacute;a a Israel.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">El pueblo de Dios necesitaba ayuda pues sus enemigos, los filisteos, maltrataban a los israelitas y este ni&ntilde;o ser&iacute;a el hombre m&aacute;s fuerte del mundo y los defender&iacute;a. Con el tiempo la mujer dio a luz un var&oacute;n, y le puso por nombre </span></span></span><span style="color: #9bbb59;"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Sans&oacute;n</span></span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">, el ni&ntilde;o creci&oacute; y Dios lo bendijo, y el Esp&iacute;ritu empez&oacute; a manifestarse en &eacute;l. </span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Sans&oacute;n llego a ser muy fuerte un d&iacute;a pele&oacute; con un le&oacute;n sin tener ninguna arma en su mano y le mat&oacute;. Otro d&iacute;a atrapo trescientos zorros, y les at&oacute; a sus colas y les prendi&oacute; fuego, dej&aacute;ndolos libres para que corrieran por los campos de los filisteos. Sans&oacute;n se dejo atrapar, lo ataron y lo entregaron para ser matado por los filisteos, pero el Esp&iacute;ritu de Dios vino sobre Sans&oacute;n y le liber&oacute; y con una quijada de un asno muerto mato a mil enemigos. Una noche los filisteos le atraparon en una ciudad y cerraron con llave los portones de la ciudad, pero Sans&oacute;n sali&oacute; derrumbando los portones; los filisteos no sab&iacute;an como detener a Sans&oacute;n porque era muy fuerte, as&iacute; que planearon que una mujer llamada Dalila le enamorara y le contara el secreto de su fuerza, pero Sans&oacute;n le fallo a Dios, se embriag&oacute; y comparti&oacute; el secreto de su fuerza con Dalila, y ella llamo a los filisteos para que le cortaran el cabello mientras dorm&iacute;a. Los filisteos atacaron a Sans&oacute;n que no se pudo defender ya que le hab&iacute;an cortado el cabello y perdido su fuerza, le sacaron sus ojos y le esclavizaron. </span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: large;"><span lang="es-ES">Al pasar los a&ntilde;os, un d&iacute;a los filisteos hicieron una fiesta y alabaron a sus dioses por entregar en sus manos a Sans&oacute;n, mandaron a llamar a Sans&oacute;n para burlarse de el, y al ni&ntilde;o que lo guiaba Sans&oacute;n le pidi&oacute; que le colocara sus manos en las columnas del templo, y como a Sans&oacute;n le hab&iacute;a vuelto a crecer su cabello, or&oacute; a Dios para que le regresara su fuerza, y empujo las columnas y todo el templo cay&oacute; en ruina, matando a filisteos y a &eacute;l con ellos.</span></span></span></p>
                            </body>
                            </html>',
            'image' => 'images/histories/10-06-2018_21-06-46.jpeg',
            'video' => '',
        ]);

            LetterSoup::create([
                'history_id' => $history->id,
                'words' => '[{"word":"BEBE","id":1528782233656},{"word":"JUEZ","id":1528782267482},{"word":"ASNO","id":1528782279354},{"word":"MANOA","id":1528782287234},{"word":"ISRAEL","id":1528782295842},{"word":"FUERTE","id":1528782308410},{"word":"CORTAR","id":1528782317441},{"word":"QUIJADA","id":1528782323257},{"word":"DALILA","id":1528782367386},{"word":"SECRETO","id":1528782376953}]',
            ]);


        //Historias (Jueveniles)

        /*$history = History::create([
            'user_id' => 1,
            'category_id' => 3,
            'title' => 'Noé',
            'sub_title' => 'Noé, el Arca y el Gran Diluvio',
            'description' => 'Fascinante historia sobre la construcción de un arca y el pacto de Dios con el mundo',
            'content' => '<!DOCTYPE html>
                            <html>
                            <head>
                            </head>
                            <body>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: center;" align="center"><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: x-large;"><strong>No&eacute;, el Arca y el Gran Diluvio</strong></span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: center;" align="center">&nbsp;</p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Estas son las generaciones de No&eacute;: No&eacute;, var&oacute;n justo,&nbsp;era perfecto en sus generaciones; con Dios camin&oacute; No&eacute;. Y engendr&oacute; No&eacute; tres hijos: a </span></span><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Sem, a Cam y a Jafet.</span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;"> Y se corrompi&oacute; la tierra delante de Dios, y estaba la tierra llena de violencia. Y mir&oacute; Dios la tierra, y he aqu&iacute; que estaba corrompida; porque toda carne hab&iacute;a corrompido su camino sobre la tierra.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Dijo, pues, Dios a No&eacute;: </span></span><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">He decidido el fin de todo ser, porque la tierra est&aacute; llena de violencia a causa de ellos; y he aqu&iacute; que yo los destruir&eacute; con la tierra.</span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;"> Hazte un arca de madera de gofer; har&aacute;s aposentos en el arca, y la calafatear&aacute;s con brea por dentro y por fuera. Y de esta manera la har&aacute;s: de trescientos codos la longitud del arca, de cincuenta codos su anchura, y de treinta codos su altura. Una ventana har&aacute;s al arca, y la acabar&aacute;s a un codo de elevaci&oacute;n por la parte de arriba; y pondr&aacute;s la puerta del arca a su lado; y le har&aacute;s piso bajo, segundo y tercero. </span></span><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y he aqu&iacute; que yo traigo un diluvio de aguas sobre la tierra, para destruir toda carne en que haya esp&iacute;ritu de vida debajo del cielo; todo lo que hay en la tierra morir&aacute;.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">M&aacute;s establecer&eacute; mi pacto contigo, y entrar&aacute;s en el arca t&uacute;, tus hijos, tu mujer, y las mujeres de tus hijos contigo.</span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;"> Y de todo lo que vive, de toda carne, dos de cada especie meter&aacute;s en el arca, para que tengan vida contigo; macho y hembra ser&aacute;n. De las aves, de las bestias y de todo reptil de la tierra seg&uacute;n su especie, dos de cada especie entrar&aacute;n contigo, para que tengan vida. Y toma contigo de todo alimento que se come, y almac&eacute;nalo, y servir&aacute; de sustento para ti y para ellos.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y lo hizo as&iacute; No&eacute;;&nbsp;hizo conforme a todo lo que Dios le mand&oacute;. Dijo luego Jehov&aacute; a No&eacute;: </span></span><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Entra t&uacute; y toda tu casa en el arca; porque a ti he visto justo delante de m&iacute; en esta generaci&oacute;n. </span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;">E hizo No&eacute; conforme a todo lo que le mand&oacute; Jehov&aacute;. Era No&eacute; de seiscientos a&ntilde;os cuando el diluvio de las aguas vino sobre la tierra. Y por causa de las aguas del diluvio entr&oacute; No&eacute; al arca,&nbsp;y con &eacute;l sus hijos, su mujer, y las mujeres de sus hijos. Y los animales de dos en dos entraron con No&eacute; en el arca; macho y hembra, como mand&oacute; Dios a No&eacute;. El a&ntilde;o seiscientos de la vida de No&eacute;, en el mes segundo, a los diecisiete d&iacute;as del mes, aquel d&iacute;a fueron rotas todas las fuentes del grande abismo, y las cataratas de los cielos fueron abiertas,&nbsp;y hubo lluvia sobre la tierra cuarenta d&iacute;as y cuarenta noches. </span></span><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y Jehov&aacute; le cerr&oacute; la puerta.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y fue el diluvio cuarenta d&iacute;as sobre la tierra; y las aguas crecieron, y alzaron el arca, y se elev&oacute; sobre la tierra. </span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y subieron las aguas y crecieron en gran manera sobre la tierra; y flotaba el arca sobre la superficie de las aguas. Y todos los montes altos que hab&iacute;a debajo de todos los cielos, fueron cubiertos. Quince codos m&aacute;s alto subieron las aguas, despu&eacute;s que fueron cubiertos los montes. Y muri&oacute; toda carne que se mueve sobre la tierra, as&iacute; de aves como de ganado y de bestias, y de todo reptil que se arrastra sobre la tierra, y todo hombre. Todo lo que ten&iacute;a aliento de esp&iacute;ritu de vida en sus narices, todo lo que hab&iacute;a en la tierra, muri&oacute;.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y qued&oacute; solamente No&eacute;, y los que con &eacute;l estaban en el arca. Y prevalecieron las aguas sobre la tierra ciento cincuenta d&iacute;as. Y se acord&oacute; Dios de No&eacute;, y de todos los animales, y de todas las bestias que estaban con &eacute;l en el arca; e hizo pasar Dios un viento sobre la tierra, y disminuyeron las aguas.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y se cerraron las fuentes del abismo y las cataratas de los cielos; y la lluvia de los cielos fue detenida. Y las aguas decrec&iacute;an gradualmente de sobre la tierra; y se retiraron las aguas al cabo de ciento cincuenta d&iacute;as. </span></span><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y repos&oacute; el arca en el mes s&eacute;ptimo, a los diecisiete d&iacute;as del mes, sobre los montes de Ararat.</span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;"> Y las aguas fueron decreciendo hasta el mes d&eacute;cimo; en el d&eacute;cimo, al primero del mes, se descubrieron las cimas de los montes.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Sucedi&oacute; que al cabo de cuarenta d&iacute;as abri&oacute; No&eacute; la ventana del arca que hab&iacute;a hecho, y envi&oacute; un cuervo, el cual sali&oacute;, y estuvo yendo y volviendo hasta que las aguas se secaron sobre la tierra. Envi&oacute; tambi&eacute;n de s&iacute; una paloma, para ver si las aguas se hab&iacute;an retirado de sobre la faz de la tierra. Y no hall&oacute; la paloma donde sentar la planta de su pie, y volvi&oacute; a &eacute;l al arca, porque las aguas estaban a&uacute;n sobre la faz de toda la tierra. Entonces &eacute;l extendi&oacute; su mano, y tom&aacute;ndola, la hizo entrar consigo en el arca.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Esper&oacute; a&uacute;n otros siete d&iacute;as, y volvi&oacute; a enviar la paloma fuera del arca. Y la paloma volvi&oacute; a &eacute;l a la hora de la tarde; y he aqu&iacute; que tra&iacute;a una hoja de olivo en el pico; y entendi&oacute; No&eacute; que las aguas se hab&iacute;an retirado de sobre la tierra. Y esper&oacute; a&uacute;n otros siete d&iacute;as, y envi&oacute; la paloma, la cual no volvi&oacute; ya m&aacute;s a &eacute;l.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y sucedi&oacute; que en el a&ntilde;o seiscientos uno de No&eacute;, en el mes primero, el d&iacute;a primero del mes, las aguas se secaron sobre la tierra; y quit&oacute; No&eacute; la cubierta del arca, y mir&oacute;, y he aqu&iacute; que la faz de la tierra estaba seca. Y en el mes segundo, a los veintisiete d&iacute;as del mes, se sec&oacute; la tierra.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Entonces habl&oacute; Dios a No&eacute;, diciendo: </span></span><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Sal del arca t&uacute;, y tu mujer, y tus hijos, y las mujeres de tus hijos contigo. Todos los animales que est&aacute;n contigo de toda carne, de aves y de bestias y de todo reptil que se arrastra sobre la tierra, sacar&aacute;s contigo; y vayan por la tierra, y fructifiquen y multipl&iacute;quense sobre la tierra.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y edific&oacute; No&eacute; un altar a Jehov&aacute;, y tom&oacute; de todo animal limpio y de toda ave limpia, y ofreci&oacute; holocausto en el altar. Y percibi&oacute; Jehov&aacute; olor grato; y dijo Jehov&aacute; en su coraz&oacute;n: </span></span><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">No volver&eacute; m&aacute;s a maldecir la tierra por causa del hombre; porque el intento del coraz&oacute;n del hombre es malo desde su juventud; ni volver&eacute; m&aacute;s a destruir todo ser viviente, como he hecho.</span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;"> Mientras la tierra permanezca, no cesar&aacute;n la sementera y la siega, el fr&iacute;o y el calor, el verano y el invierno, y el d&iacute;a y la noche.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Bendijo Dios a No&eacute; y a sus hijos, y les dijo: </span></span><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Fructificad y multiplicaos, y llenad la tierra.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y habl&oacute; Dios a No&eacute; y a sus hijos con &eacute;l, diciendo</span></span><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">: He aqu&iacute; que yo establezco mi pacto con vosotros, y con vuestros descendientes despu&eacute;s de vosotros; y con todo ser viviente que est&aacute; con vosotros; aves, animales y toda bestia de la tierra que est&aacute; con vosotros, desde todos los que salieron del arca hasta todo animal de la tierra.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Establecer&eacute; mi pacto con vosotros, y no exterminar&eacute; ya m&aacute;s toda carne con aguas de diluvio, ni habr&aacute; m&aacute;s diluvio para destruir la tierra.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y dijo Dios: </span></span><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Esta es la se&ntilde;al del pacto que yo establezco entre m&iacute; y vosotros y todo ser viviente que est&aacute; con vosotros, por siglos perpetuos:</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="color: #7030a0;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Mi arco he puesto en las nubes, el cual ser&aacute; por se&ntilde;al del pacto entre m&iacute; y la tierra. Y suceder&aacute; que cuando haga venir nubes sobre la tierra, se dejar&aacute; ver entonces mi arco en las nubes. Y me acordar&eacute; del pacto m&iacute;o, que hay entre m&iacute; y vosotros y todo ser viviente de toda carne; y no habr&aacute; m&aacute;s diluvio de aguas para destruir toda carne.</span></span></span></p>
                            </body>
                            </html>',
            'image' => 'images/histories/11-06-2018_20-06-03.jpeg',
            'video' => '',
        ]);

            LetterSoup::create([
                'history_id' => $history->id,
                'words' => '[{"word":"NOE","id":1528782759442},{"word":"ARCA","id":1528782791175},{"word":"AGUA","id":1528782799168},{"word":"LLUVIA","id":1528782800295},{"word":"MACHO","id":1528782800767},{"word":"HEMBRA","id":1528782801160},{"word":"DIAS","id":1528782801552},{"word":"PALOMA","id":1528782801912},{"word":"ARCOIRIS","id":1528782827185},{"word":"ANIMALES","id":1528782827544},{"word":"ARARAT","id":1528782827719},{"word":"FAMILIA","id":1528782827880},{"word":"MADERA","id":1528782828064},{"word":"DILUVIO","id":1528782847968},{"word":"MUNDO","id":1528782848392},{"word":"GENTE","id":1528782848552}]',
            ]);  */

        $history = History::create([
            'user_id' => 1,
            'category_id' => 3,
            'title' => 'Abraham',
            'sub_title' => 'Abraham e Isaac',
            'description' => 'Un hombre escogido por Dios, lleno de fe y amor.',
            'content' => '<!DOCTYPE html>
                            <html>
                            <head>
                            </head>
                            <body>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: center;" align="center"><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: x-large;">Abraham e Isaac</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%;" align="center">&nbsp;</p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Aconteci&oacute; despu&eacute;s de estas cosas, que prob&oacute; Dios a Abraham, y le dijo: </span></span><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Abraham.</span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;"> Y &eacute;l respondi&oacute;: </span></span><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Heme aqu&iacute;</span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;">.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y dijo: </span></span><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Toma ahora tu hijo, tu &uacute;nico, Isaac, a quien amas, y vete a tierra de Moriah, y ofr&eacute;celo all&iacute; en holocausto sobre uno de los montes que yo te dir&eacute;.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify">&nbsp;<span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y Abraham se levant&oacute; muy de ma&ntilde;ana, y enalbard&oacute; su asno, y tom&oacute; consigo dos siervos suyos, y a Isaac su hijo; y cort&oacute; le&ntilde;a para el holocausto, y se levant&oacute;, y fue al lugar que Dios le dijo.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Al tercer d&iacute;a alz&oacute; Abraham sus ojos, y vio el lugar de lejos.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Entonces dijo Abraham a sus siervos: Esperad aqu&iacute; con el asno, y yo y el muchacho iremos hasta all&iacute; y </span></span><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">adoraremos, y volveremos a vosotros.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y tom&oacute; Abraham la le&ntilde;a del holocausto, y la puso sobre Isaac su hijo, y &eacute;l tom&oacute; en su mano el fuego y el cuchillo; y fueron ambos juntos.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Entonces habl&oacute; Isaac a Abraham su padre, y dijo: Padre m&iacute;o. Y &eacute;l respondi&oacute;: Heme aqu&iacute;, mi hijo. Y &eacute;l dijo: He aqu&iacute; el fuego y la le&ntilde;a; mas </span></span><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">&iquest;d&oacute;nde est&aacute; el cordero para el holocausto?</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y respondi&oacute; Abraham: </span></span><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Dios se proveer&aacute; de cordero para el holocausto</span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;">, hijo m&iacute;o. E iban juntos.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y cuando llegaron al lugar que Dios le hab&iacute;a dicho, edific&oacute; all&iacute; Abraham un altar, y compuso la le&ntilde;a, y at&oacute; a Isaac su hijo, y lo puso en el altar&nbsp;sobre la le&ntilde;a.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y extendi&oacute; Abraham su mano y tom&oacute; el cuchillo para degollar a su hijo.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Entonces el &aacute;ngel de Jehov&aacute; le dio voces desde el cielo, y dijo: </span></span><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Abraham, Abraham.</span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;"> Y &eacute;l respondi&oacute;: </span></span><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Heme aqu&iacute;.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y dijo: </span></span><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">No extiendas tu mano sobre el muchacho, ni le hagas nada; porque ya conozco que temes a Dios, por cuanto no me rehusaste tu hijo, tu &uacute;nico.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Entonces alz&oacute; Abraham sus ojos y mir&oacute;, y he aqu&iacute; a sus espaldas un carnero trabado en un zarzal por sus cuernos; y fue Abraham y tom&oacute; el carnero, y lo ofreci&oacute; en holocausto en lugar de su hijo.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y llam&oacute; Abraham el nombre de aquel lugar, </span></span><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Jehov&aacute; proveer&aacute;</span></span></span><span style="font-family: Courgette, serif;"><span style="font-size: medium;">.&nbsp;Por tanto se dice hoy: En el monte de Jehov&aacute; ser&aacute; provisto.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y llam&oacute; el &aacute;ngel de Jehov&aacute; a Abraham por segunda vez desde el cielo,</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y dijo: </span></span><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Por m&iacute; mismo he jurado, dice Jehov&aacute;, que por cuanto has hecho esto, y no me has rehusado tu hijo, tu &uacute;nico hijo;</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">De cierto te bendecir&eacute;, y multiplicar&eacute;&nbsp;tu descendencia como las estrellas del cielo y como la arena que est&aacute; a la orilla del mar;&nbsp;y tu descendencia poseer&aacute; las puertas de sus enemigos.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="color: #00b050;"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">En tu simiente ser&aacute;n benditas todas las naciones de la tierra,&nbsp;por cuanto obedeciste a mi voz.</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;"><span style="font-size: medium;">Y volvi&oacute; Abraham a sus siervos, y se levantaron y se fueron juntos a Beerseba; y habit&oacute; Abraham en Beerseba.</span></span></p>
                            </body>
                            </html>',
            'image' => 'images/histories/11-06-2018_20-06-20.jpeg',
            'video' => '',
        ]);

            LetterSoup::create([
                'history_id' => $history->id,
                'words' => '[{"word":"AMOR","id":1528782624400},{"word":"HIJO","id":1528782671617},{"word":"ALTO","id":1528782681889},{"word":"ISAAC","id":1528782689280},{"word":"\u00c1NGEL","id":1528782694256},{"word":"ORDEN","id":1528782698280},{"word":"PRUEBA","id":1528782701002},{"word":"ALTAR","id":1528782705729},{"word":"ABRAHAM","id":1528782708264},{"word":"TEMOR","id":1528782715192},{"word":"AMADO","id":1528782715408},{"word":"CONFIAR","id":1528782724641},{"word":"CUCHILLO","id":1528782736240},{"word":"ADORAR","id":1528782742056},{"word":"PROVEE","id":1528782742496},{"word":"OBEDECER","id":1528782742872}]',
            ]);

        $history = History::create([
            'user_id' => 1,
            'category_id' => 3,
            'title' => 'Sansón',
            'sub_title' => 'Sansón y su Fuerza',
            'description' => 'un hombre increíblemente fuerte, que pasará por una dura prueba, para demostrar su obediencia',
            'content' => '<!DOCTYPE html>
                            <html>
                            <head>
                            </head>
                            <body>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: center;" align="center"><span style="color: #943634;"><span style="font-family: Courgette, serif;"><span style="font-size: x-large;">Sans&oacute;n y su Fuerza</span></span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: center;" align="center">&nbsp;</p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Los hijos de Israel volvieron a hacer lo malo ante los ojos de Jehov&aacute;; y Jehov&aacute; los entreg&oacute; en mano de los filisteos por cuarenta a&ntilde;os.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Y hab&iacute;a un hombre de Zora, de la tribu de Dan, el cual se llamaba Manoa; y su mujer era est&eacute;ril, y nunca hab&iacute;a tenido hijos. A esta mujer apareci&oacute; el &aacute;ngel de Jehov&aacute;, y le dijo: </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">He aqu&iacute; que t&uacute; eres est&eacute;ril, y nunca has tenido hijos; pero concebir&aacute;s y dar&aacute;s a luz un hijo.</span></span><span style="font-family: Courgette, serif;"> Ahora, pues, no bebas vino ni sidra, ni comas cosa inmunda. </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">Pues he aqu&iacute; que concebir&aacute;s y dar&aacute;s a luz un hijo; y navaja no pasar&aacute; sobre su cabeza, porque el ni&ntilde;o ser&aacute; nazareo&nbsp;a Dios desde su nacimiento, y &eacute;l comenzar&aacute; a salvar a Israel de mano de los filisteos.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Y la mujer vino y se lo cont&oacute; a su marido, diciendo: Un var&oacute;n de Dios vino a m&iacute;, cuyo aspecto era como el aspecto de un &aacute;ngel de Dios, temible en gran manera; y no le pregunt&eacute; de d&oacute;nde ni qui&eacute;n era, ni tampoco &eacute;l me dijo su nombre. Y me dijo: He aqu&iacute; que t&uacute; concebir&aacute;s, y dar&aacute;s a luz un hijo; por tanto, ahora no bebas vino, ni sidra, ni comas cosa inmunda, porque este ni&ntilde;o ser&aacute; nazareo a Dios desde su nacimiento hasta el d&iacute;a de su muerte.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Entonces or&oacute; Manoa a Jehov&aacute;, y dijo: Ah, Se&ntilde;or m&iacute;o, yo te ruego que aquel var&oacute;n de Dios que enviaste, vuelva ahora a venir a nosotros, y nos ense&ntilde;e lo que hayamos de hacer con el ni&ntilde;o que ha de nacer. Y Dios oy&oacute; la voz de Manoa; y el &aacute;ngel de Dios volvi&oacute; otra vez a la mujer, estando ella en el campo; mas su marido Manoa no estaba con ella. Y la mujer corri&oacute; prontamente a avisarle a su marido, dici&eacute;ndole: Mira que se me ha aparecido aquel var&oacute;n que vino a m&iacute; el otro d&iacute;a.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Y se levant&oacute; Manoa, y sigui&oacute; a su mujer; y vino al var&oacute;n y le dijo: &iquest;Eres t&uacute; aquel var&oacute;n que habl&oacute; a la mujer? Y &eacute;l dijo: </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">Yo soy. </span></span><span style="font-family: Courgette, serif;">Entonces Manoa dijo: Cuando tus palabras se cumplan, &iquest;c&oacute;mo debe ser la manera de vivir del ni&ntilde;o, y qu&eacute; debemos hacer con &eacute;l?</span> <span style="font-family: Courgette, serif;">Y el &aacute;ngel de Jehov&aacute; respondi&oacute; a Manoa: </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">La mujer se guardar&aacute; de todas las cosas que yo le dije. No tomar&aacute; nada que proceda de la vid; no beber&aacute; vino ni sidra, y no comer&aacute; cosa inmunda; guardar&aacute; todo lo que le mand&eacute;.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Y la mujer dio a luz un hijo, y le puso por nombre </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">Sans&oacute;n.</span></span><span style="font-family: Courgette, serif;"> Y el ni&ntilde;o creci&oacute;, y Jehov&aacute; lo bendijo. </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">Y el Esp&iacute;ritu de Jehov&aacute; comenz&oacute; a manifestarse en &eacute;l </span></span><span style="font-family: Courgette, serif;">en los campamentos de Dan, entre Zora y Estaol.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">En una ocasi&oacute;n Sans&oacute;n mat&oacute; a mil enemigos con la </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">quijada de un asno</span></span><span style="font-family: Courgette, serif;"> y en otra derrib&oacute; </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">los portones de una ciudad </span></span><span style="font-family: Courgette, serif;">ya que lo hab&iacute;an atrapado y de esta manera escap&oacute;, todo esto era gracias a la fuerza que el ten&iacute;a ya que el Esp&iacute;ritu de Dios estaba sobre el.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Despu&eacute;s de esto aconteci&oacute; que se enamor&oacute; de una mujer en el valle de Sorec, la cual se llamaba </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">Dalila.</span></span><span style="font-family: Courgette, serif;"> Y vinieron a ella los pr&iacute;ncipes de los filisteos, y le dijeron: Eng&aacute;&ntilde;ale e inf&oacute;rmate en qu&eacute; consiste su gran fuerza, y c&oacute;mo lo podr&iacute;amos vencer, para que lo atemos y lo dominemos; y cada uno de nosotros te dar&aacute; mil cien siclos de plata.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Y Dalila dijo a Sans&oacute;n: Yo te ruego que me declares en qu&eacute; consiste tu gran fuerza, y c&oacute;mo podr&aacute;s ser atado para ser dominado. Y le respondi&oacute; Sans&oacute;n: Si me ataren con siete mimbres verdes que a&uacute;n no est&eacute;n enjutos, entonces me debilitar&eacute; y ser&eacute; como cualquiera de los hombres. Y los pr&iacute;ncipes de los filisteos le trajeron siete mimbres verdes que a&uacute;n no estaban enjutos, y ella le at&oacute; con ellos. Y ella ten&iacute;a hombres en acecho en el aposento. Entonces ella le dijo: </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">&iexcl;Sans&oacute;n, los filisteos contra ti!</span></span><span style="font-family: Courgette, serif;"> Y &eacute;l rompi&oacute; los mimbres, como se rompe una cuerda de estopa cuando toca el fuego; y no se supo el secreto de su fuerza.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Entonces Dalila dijo a Sans&oacute;n: He aqu&iacute; t&uacute; me has enga&ntilde;ado, y me has dicho mentiras; desc&uacute;breme, pues, ahora, te ruego, c&oacute;mo podr&aacute;s ser atado. Y &eacute;l le dijo: Si me ataren fuertemente con cuerdas nuevas que no se hayan usado, yo me debilitar&eacute;, y ser&eacute; como cualquiera de los hombres. Y Dalila tom&oacute; cuerdas nuevas, y le at&oacute; con ellas, y le dijo: </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">&iexcl;Sans&oacute;n, los filisteos sobre ti! </span></span><span style="font-family: Courgette, serif;">Y los esp&iacute;as estaban en el aposento. M&aacute;s &eacute;l las rompi&oacute; de sus brazos como un hilo. Y Dalila dijo a Sans&oacute;n: Hasta ahora me enga&ntilde;as, y tratas conmigo con mentiras. Desc&uacute;breme, pues, ahora, c&oacute;mo podr&aacute;s ser atado. El entonces le dijo: Si tejieres siete guedejas de mi cabeza con la tela y las asegurares con la estaca. Y ella las asegur&oacute; con la estaca, y le dijo: </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">&iexcl;Sans&oacute;n, los filisteos sobre ti!</span></span><span style="font-family: Courgette, serif;"> Mas despertando &eacute;l de su sue&ntilde;o, arranc&oacute; la estaca del telar con la tela.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Y ella le dijo: &iquest;C&oacute;mo dices: Yo te amo, cuando tu coraz&oacute;n no est&aacute; conmigo? Ya me has enga&ntilde;ado tres veces, y no me has descubierto a&uacute;n en qu&eacute; consiste tu gran fuerza.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Y aconteci&oacute; que, presion&aacute;ndole ella cada d&iacute;a con sus palabras e importun&aacute;ndole, su alma fue reducida a mortal angustia.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Le descubri&oacute;, pues, todo su coraz&oacute;n, y le dijo: </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">Nunca a mi cabeza lleg&oacute; navaja; porque soy nazareo de Dios desde el vientre de mi madre. Si fuere rapado, mi fuerza se apartar&aacute; de m&iacute;, y me debilitar&eacute; y ser&eacute; como todos los hombres.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Viendo Dalila que &eacute;l le hab&iacute;a descubierto todo su coraz&oacute;n, envi&oacute; a llamar a los principales de los filisteos, diciendo: Venid esta vez, porque &eacute;l me ha descubierto todo su coraz&oacute;n. Y los principales de los filisteos vinieron a ella, trayendo en su mano el dinero. Y ella hizo que &eacute;l se durmiese sobre sus rodillas, y llam&oacute; a un hombre, quien le rap&oacute; las siete guedejas de su cabeza; y ella comenz&oacute; a afligirlo, pues su fuerza se apart&oacute; de &eacute;l. Y le dijo: </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">&iexcl;Sans&oacute;n, los filisteos sobre ti!</span></span><span style="font-family: Courgette, serif;"> Y luego que despert&oacute; &eacute;l de su sue&ntilde;o, se dijo: Esta vez saldr&eacute; como las otras y me escapar&eacute;. </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">Pero &eacute;l no sab&iacute;a que Jehov&aacute; ya se hab&iacute;a apartado de &eacute;l.</span></span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Mas los filisteos le echaron mano, y le sacaron los ojos, y le llevaron a Gaza; y le ataron con cadenas para que moliese en la c&aacute;rcel.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Y el cabello de su cabeza comenz&oacute; a crecer, despu&eacute;s que fue rapado.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Entonces los principales de los filisteos se juntaron para ofrecer sacrificio a Dag&oacute;n su dios y para alegrarse; y dijeron: Nuestro dios entreg&oacute; en nuestras manos a Sans&oacute;n nuestro enemigo. Y vi&eacute;ndolo el pueblo, alabaron a su dios, diciendo: Nuestro dios entreg&oacute; en nuestras manos a nuestro enemigo, y al destruidor de nuestra tierra, el cual hab&iacute;a dado muerte a muchos de nosotros. Y aconteci&oacute; que cuando sintieron alegr&iacute;a en su coraz&oacute;n, dijeron: Llamad a Sans&oacute;n, para que nos divierta. Y llamaron a Sans&oacute;n de la c&aacute;rcel, y sirvi&oacute; de juguete delante de ellos; y lo pusieron entre las columnas.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Entonces Sans&oacute;n dijo al joven que le guiaba de la mano: Ac&eacute;rcame, y hazme palpar las columnas sobre las que descansa la casa, para que me apoye sobre ellas.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Y la casa estaba llena de hombres y mujeres, y todos los principales de los filisteos estaban all&iacute;; y en el piso alto hab&iacute;a como tres mil hombres y mujeres, que estaban mirando el escarnio de Sans&oacute;n.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Entonces clam&oacute; Sans&oacute;n a Jehov&aacute;, y dijo: </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">Se&ntilde;or Jehov&aacute;, acu&eacute;rdate ahora de m&iacute;, y fortal&eacute;ceme, te ruego, solamente esta vez, oh Dios, para que de una vez tome venganza de los filisteos por mis dos ojos. </span></span><span style="font-family: Courgette, serif;">Asi&oacute; luego Sans&oacute;n las dos columnas de en medio, sobre las que descansaba la casa, y ech&oacute; todo su peso sobre ellas, su mano derecha sobre una y su mano izquierda sobre la otra.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Y dijo Sans&oacute;n: </span><span style="color: #943634;"><span style="font-family: Courgette, serif;">Muera yo con los filisteos.</span></span><span style="font-family: Courgette, serif;"> Entonces se inclin&oacute; con toda su fuerza, y cay&oacute; la casa sobre los principales, y sobre todo el pueblo que estaba en ella. Y los que mat&oacute; al morir fueron muchos m&aacute;s que los que hab&iacute;a matado durante su vida.</span></p>
                            <p class="western" lang="es-VE" style="margin-bottom: 0.35cm; line-height: 115%; text-align: justify;" align="justify"><span style="font-family: Courgette, serif;">Y descendieron sus hermanos y toda la casa de su padre, y le tomaron, y le llevaron, y le sepultaron entre Zora y Estaol, en el sepulcro de su padre Manoa. Y &eacute;l juzg&oacute; a Israel veinte a&ntilde;os.</span></p>
                            </body>
                            </html>',
            'image' => 'images/histories/11-06-2018_20-06-23.jpeg',
            'video' => '',
        ]);

            LetterSoup::create([
                'history_id' => $history->id,
                'words' => '[{"word":"BEBE","id":1528782233656},{"word":"JUEZ","id":1528782267482},{"word":"ASNO","id":1528782279354},{"word":"MANOA","id":1528782287234},{"word":"ISRAEL","id":1528782295842},{"word":"FUERTE","id":1528782308410},{"word":"CORTAR","id":1528782317441},{"word":"QUIJADA","id":1528782323257},{"word":"DALILA","id":1528782367386},{"word":"SECRETO","id":1528782376953},{"word":"ESPIRITU","id":1528782385753},{"word":"CRECER","id":1528782392409},{"word":"OJOS","id":1528782398737},{"word":"NI\u00d1O","id":1528782405626},{"word":"CABELLO","id":1528782412481}]',
            ]);

        $point_array = [
            20, 40, 60, 80, 100
        ];

        $users_array = [
            22, 65, 75, 57, 10, 55, 8, 2, 33, 45, 75, 57, 80
        ];

        for ($i=0; $i < 22; $i++) {
            Point::create([
                'point' => $point_array[rand(0, 4)],
                'user_id' => $users_array[rand(0, 12)],
                'test_id' => $tests->id,
            ]);
        }



    }
}
